import assert from "node:assert/strict";
import fs from "node:fs";

const app = fs.readFileSync(new URL("../app.js", import.meta.url), "utf8");
const css = fs.readFileSync(new URL("../styles.css", import.meta.url), "utf8");
const config = fs.readFileSync(new URL("../study-config.js", import.meta.url), "utf8");
const index = fs.readFileSync(new URL("../index.html", import.meta.url), "utf8");

assert.match(app, /plateCard\(0\)/);
assert.doesNotMatch(app, /plateCard\(1,/);
assert.doesNotMatch(app, /Plate 2/);
assert.match(app, /Instruction &amp; Comprehension Test/);
assert.match(app, /Which version would motivate you more to continue reading, based on its visual appearance\?/);
assert.match(app, /<h1>Main Study<\/h1>/);
assert.match(app, /<h1>You completed the task\.<\/h1>/);
assert.doesNotMatch(app, /downloadPreviewLog|Download preview log|Your first impression|Your responses are ready/);
assert.doesNotMatch(app, /class="eyebrow"/);
assert.match(app, /sandbox="allow-same-origin"/);
assert.match(app, /measureFrameContentHeight/);
assert.match(app, /This study can only be completed on a laptop or desktop computer using a mouse or trackpad\./);
assert.match(app, /Mobile phones and tablets are not supported\./);
assert.match(app, /<span>1,000 ms<\/span>/);
assert.match(app, /comprehensionOption\("duration", "one_second", "About one second"\)/);
assert.doesNotMatch(app, /half_second|About half a second|<span>500 ms<\/span>/);
assert.match(app, /114 brief visual comparisons in three sets/);
assert.match(app, /Optional break/);
assert.match(app, /Skip break and continue/);
assert.match(app, /action: "checkpoint"/);
assert.match(app, /action: "confirm_record"/);
assert.match(app, /function retryMissingTrials/);
assert.match(app, /function confirmTrialCheckpoint/);
assert.match(app, /confirmationMode: "checkpoint"/);
assert.match(config, /version: "2026-08-25-v7"/);
assert.match(config, /trialCount: 114/);
assert.match(config, /breakAfterTrials: \[38, 76\]/);
assert.match(config, /recommendedBreakMs: 60000/);
assert.match(config, /dataRequestTimeoutMs: 60000/);
assert.ok(config.includes('dataEndpoint: "https://script.google.com/macros/s/'));
assert.ok(config.includes('complete: "https://app.prolific.com/submissions/complete?cc=CW2P6FV4"'));
assert.ok(config.includes('screenedOut: "https://app.prolific.com/submissions/complete?cc=C1JJDH8M"'));
assert.ok(config.includes('incompatibleDevice: "https://app.prolific.com/submissions/complete?cc=CG4A1FAO"'));
assert.ok(config.includes('failedComprehension: "https://app.prolific.com/submissions/complete?cc=COI7JSKM"'));
assert.ok(config.includes('noConsent: "https://app.prolific.com/submissions/complete?cc=CYE28F39"'));
assert.match(config, /exposureMs: 1000/);
assert.ok(index.includes("app.js?v=2026-08-26-v7-data-timeout"));
assert.ok(index.includes("study-config.js?v=2026-08-26-v7-data-timeout"));
assert.equal((app.match(/CONFIG\.network\.dataRequestTimeoutMs/g) || []).length, 6);
assert.doesNotMatch(app, /function jsonp\(endpoint, query, timeoutMs = 10000\)/);
assert.match(app, /\.json\?v=" \+ encodeURIComponent\(CONFIG\.version\)/);
assert.match(app, /terminateEarly\("incompatible_device"\)/);
assert.match(app, /terminateEarly\("eligibility_criteria"\)/);
assert.match(app, /terminateEarly\("color_vision_check"\)/);
assert.match(app, /terminateEarly\("failed_comprehension_twice"\)/);
assert.match(app, /redirectTo\(CONFIG\.redirects\.complete\)/);
assert.match(app, /redirectTo\(CONFIG\.redirects\.noConsent\)/);
assert.match(app, /function redirectTo\(url\) \{\s+if \(isPreview\)[\s\S]+?if \(url\)/);
assert.match(app, /function resetPreview\(\) \{\s+if \(!isPreview\) return;\s+suppressUnloadSave = true;\s+localStorage\.removeItem\(storageKey\);\s+window\.location\.reload\(\);\s+\}/);
assert.equal((app.match(/addEventListener\("click", resetPreview\)/g) || []).length, 3);
assert.match(app, /window\.addEventListener\("beforeunload", \(\) => \{\s+if \(!suppressUnloadSave\) saveLocal\(\);\s+\}\);/);
assert.equal((app.match(/localStorage\.removeItem\(storageKey\)/g) || []).length, 1);
assert.doesNotMatch(config, /failedAttention|returnSubmission/);
assert.match(css, /\.device-requirement/);
assert.match(css, /--wash: #f7f9fa;/);
assert.match(css, /--paper: #f7f9fa;/);
assert.doesNotMatch(css, /\.eyebrow/);
assert.match(css, /\.actions\.center \{ justify-content: center; \}/);

console.log("Interface copy and privacy controls verified.");
